### ISSUE TITLE
The projects page (public)

### ISSUE THREAD

**Issue by tsawler** [tsawler/nbirdt#33]
Ready for review.

https://nbirdt.verilion.com/projects

**Comment by MaraMallory** [comment]
I spoke with Jennifer about the categories for the projects page. She's wondering if we can use the same categories as for the publications page. But not have the categories appear as options if there are no projects that fall within teh category. So the category bar on the index page would only have 2 options on it for right now. Might look stupid. What do you think?

**Comment by tsawler** [comment]
This is a duplicate of #30. Same answer applies. I'll try to figure something out.
