### ISSUE TITLE
Typos in the footer & menu

### ISSUE THREAD

**Issue by MaraMallory** [tsawler/nbirdt#45]
New Brunswick **Insitute** for Research, Data**,** and Training
PO Box 4400 304 **Kieirstead** Hall
38 **Dineeen** Drive
University of New Brunswick
Fredericton, NB**,** E3B 5A3

Hi Trevor- there are some typos in the footer. Can you fix them? Institute typo and remove second comma in Institute name (they don't use oxford comma)
Kierstead is mispelled. Dineen has an extra e.
remove commma after NB in address

Also, can you left justify the footer columns? 

MENU: 
CAn you make the top menu say "About" and the first menu item should be What we do.
Data ACcess should be Data, and in the dropdown menu, the word Data should be replaced with Data access (I'm going to try to do taht myself)>

**Comment by tsawler** [comment]
Done.
